[tools]
node = ["lts"]
python = ["3.11", "3.13"]
rust = "latest"

[settings]
idiomatic_version_file_enable_tools = ["node"]

# [env]
# _.python.venv = { path = ".venv" } # https://mise.jdx.dev/lang/python.html#automatic-virtualenv-activation
