# https://alacritty.org/config-alacritty.html

[window]
decorations="None"
opacity=0.85
blur=false
option_as_alt="Both"

[font]
normal={family="BitstromWera Nerd Font"}
size=13

[env]
TERM="xterm-256color"
WINIT_X11_SCALE_FACTOR="1.0"
