# yaml-language-server: $schema=https://dlvhdr.github.io/gh-dash/configuration/gh-dash/schema.json
prSections:
- title: By Me
  filters: is:open author:@me
- title: Involved
  filters: is:open involves:@me -author:@me
- title: Needs My Review
  filters: is:open review-requested:@me
- title: By Others
  filters: is:open user:@me user:timelyschools -repo:timelyschools/timelypymodels-lib -author:@me -review:approved
- title: Approved
  filters: is:open user:@me user:timelyschools -repo:timelyschools/timelypymodels-lib review:approved
- title: Closed
  filters: is:closed user:@me user:timelyschools
issuesSections:
- title: My Issues
  filters: is:open author:@me
- title: Assigned
  filters: is:open assignee:@me
- title: Involved
  filters: is:open involves:@me -author:@me
defaults:
  preview:
    open: false
    width: 100
  prsLimit: 20
  issuesLimit: 20
  view: prs
  layout:
    prs:
      repo:
        width: 16
      author:
        width: 15
      lines:
        width: 16
      updatedAt:
        width: 5
    issues:
      repo:
        width: 15
      creator:
        width: 10
      assignees:
        width: 20
        hidden: true
      updatedAt:
        width: 7
  refetchIntervalMinutes: 30
keybindings:
  universal: []
  issues: []
  prs: []
repoPaths:
  astr0n0mer/:repo: ~/projects/:repo
  :owner/:repo: ~/projects_work/:owner/:repo
theme:
  ui:
    table:
      compact: true # INFO: https://github.com/dlvhdr/gh-dash/releases/tag/v4.5.0
      showSeparator: true
    sectionsShowCount: true
  colors:
    text:
      primary: "#E2E1ED"
      secondary: "#666CA6"
      inverted: "#242347"
      faint: "#b0b3bf"
      warning: "#F7768E"
      success: "#3DF294"
    background:
      selected: "#353535"
    border:
      primary: "#383B5B"
      secondary: "#39386B"
      faint: "#2B2B40"
pager:
  diff: "less"
confirmQuit: false
