# yaml-language-server: $schema=https://dlvhdr.github.io/gh-dash/configuration/gh-dash/schema.json
prSections:
- title: By Me
  filters: is:open author:@me
  layout:
    author:
      hidden: true
- title: Involved
  filters: is:open involves:@me -author:@me
- title: Needs My Review
  filters: is:open review-requested:@me
- title: By Others
  filters: is:open user:@me user:timelyschools -repo:timelyschools/timelypymodels-lib -author:@me -review:approved
- title: Approved
  filters: is:open user:@me user:timelyschools -repo:timelyschools/timelypymodels-lib review:approved
- title: Closed
  filters: is:closed user:@me user:timelyschools
issuesSections:
- title: My Issues
  filters: is:open author:@me
- title: Assigned
  filters: is:open assignee:@me
- title: Involved
  filters: is:open involves:@me -author:@me
defaults:
  preview:
    open: true
    width: 100
keybindings:
  universal:
    - key: g
      command: >
        cd {{.RepoPath}} && lazygit
  prs: []
repoPaths:
  astr0n0mer/:repo: ~/root/projects/:repo
  :owner/:repo: ~/root/projects_work/:owner/:repo
theme:
  ui:
    table:
      compact: false # INFO: https://github.com/dlvhdr/gh-dash/releases/tag/v4.5.0
      showSeparators: true
pager:
  diff: "less"
confirmQuit: false
