.PHONY: default
default:
	@echo "no_target_specified"

.PHONY: monkeytype.com.json
monkeytype.com.json:
	xclip -selection c -out > ~/projects/.dotfiles/websites/monkeytype.com.json

.PHONY: vimium-options.json
vimium-options.json:
	mv ~/Downloads/vimium-options.json ~/projects/.dotfiles/browser-extensions/vimium-options.json -f
