vim.keymap.set('n', '<M-h>', '<cmd>copen<CR>', { desc = "Quickfix Open" })
vim.keymap.set('n', '<M-j>', '<cmd>cnext<CR>', { desc = "Quickfix Next" })
vim.keymap.set('n', '<M-k>', '<cmd>cprev<CR>', { desc = "Quickfix Prev" })
vim.keymap.set('n', '<M-l>', '<cmd>cclose<CR>', { desc = "Quickfix Close" })
vim.keymap.set('n', '<space><space>x', '<cmd>source %<CR>')
vim.keymap.set('n', '<space>x', ':.lua<CR>')
vim.keymap.set('v', '<space>x', ':lua<CR>')
