.PHONY: setup
setup:
	curl -LO https://raw.githubusercontent.com/astr0n0mer/.dotfiles/main/_scripts/setup-macbook.sh && \
	curl -LO https://raw.githubusercontent.com/astr0n0mer/.dotfiles/main/_scripts/post-setup-macbook.sh && \
	chmod u+x setup-macbook.sh && \
	chmod u+x post-setup-macbook.sh
