.PHONY: git.plugin.zsh
git.plugin.zsh:
	echo "# ref: https://github.com/ohmyzsh/ohmyzsh/blob/master/plugins/git/git.plugin.zsh" > git.plugin.zsh \
	&& echo "# raw: https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/refs/heads/master/plugins/git/git.plugin.zsh" >> git.plugin.zsh \
	&& curl --location "https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/refs/heads/master/plugins/git/git.plugin.zsh" >> git.plugin.zsh
